### PR TITLE
Fix duplicating statistics

### LINKED ISSUE #13: %statistic_mine_block% doubles the number
### Issue
The `%statistic_mine_block%` placeholder from the Statistic module reports twice the amount of mined blocks.

### Expected behaviour
The statistic will increment by one when a block is mined.

### Actual behaviour
The statistic is incremented by two.

https://i.imgur.com/K4lrCdf.png  <- Minecraft statistic page
https://i.imgur.com/rFbFce9.png <- The placeholder (the second lore line)

### How to reproduce
1. Download the Statistic eCloud module.
2. Mine a block (or check your current mined blocks in the Minecraft statistics menu)
3. Parse the %statistic_mine_block% placeholder
4. It will show double the actual amount of blocks mined.

### PR DESCRIPTION
**Pull request by Kqliber**
Fixes #13 
Stats were looking at LEGACY_ materials and therefore duplicating older blocks. blocks that did not have legacy versions were not being duplicating.

Also fixed the expansion actually compiling/running :)

7 Mined in stats
image

PAPI returning 7
image

### CODE REVIEW

File: src/main/java/com/extendedclip/papi/expansion/mcstatistics/StatisticsExpansion.java [hunk 1]
```diff
@@ -264,6 +264,10 @@ private String calculateTotal(final OfflinePlayer player, final Statistic statis
                 continue;
             }
 
+            if (material.name().startsWith("LEGACY_")) {
```
Comment (Andre601) [inline src/main/java/com/extendedclip/papi/expansion/mcstatistics/StatisticsExpansion.java:267]: There exists a `isLegacy()` method, which may be more reliable. Not sure if it exists since the start tho or has been a more recent addition to the API.

File: pom.xml [hunk 2]
```diff
@@ -29,7 +29,7 @@
         <dependency>
             <groupId>me.clip</groupId>
             <artifactId>placeholderapi</artifactId>
-            <version>2.10.8-DEV-86</version>
+            <version>2.11.5</version>
```
Comment (Andre601) [inline pom.xml]: Why not 2.11.6?

File: src/main/java/com/extendedclip/papi/expansion/mcstatistics/StatisticsExpansion.java (hunk 1 above)
Comment (Kqliber) [reply src/main/java/com/extendedclip/papi/expansion/mcstatistics/StatisticsExpansion.java:267]: isLegacy is deprecated with reason "Do not use for any reason.", and just does the same thing anyway
Plus, for compatibility, isLegacy only exists since 1.13 and would end up with NoSuchMethodError
